### ISSUE TITLE
[Suggestion] Adding it as an applet in the new COSMIC Desktop (written in Rust)

### ISSUE THREAD

**Issue by onlyreportingissues** [Umio-Yasuno/amdgpu-profile-switcher#1]
I saw that it's written in Rust. The new COSMIC Desktop is also written in Rust (current state pre-alpha): https://github.com/pop-os/cosmic-epoch

There is also a template for adding new applets: https://github.com/edfloreshz/cosmic-app-template

Would be cool to have it available as an applet.

**Comment by Umio-Yasuno** [comment]
I do not think implementing GUI for this tool.
