### ISSUE TITLE
[Questions] Is it automated & how does it recognize the specific programs?

### ISSUE THREAD

**Issue by onlyreportingissues** [Umio-Yasuno/amdgpu-profile-switcher#2]
Hey, I googled 3D_FULL_SCREEN and profile_standard to see which one is the better "set and forget" option and then found your tool. 

(I also asked here: https://gitlab.freedesktop.org/drm/amd/-/issues/1500#note_825883 but thought I might as well ask on the project's page)

I wanted to ask how it recognizes the specific programs, if it's automated & already stable for daily usage.

**Comment by Umio-Yasuno** [comment]
The program name get from the link of `/proc/<pid>/exe` or the path from `/proc/<pid>/cmdline`.  

https://github.com/Umio-Yasuno/proc_prog_name/blob/main/src/lib.rs#L86

**Comment by Umio-Yasuno** [comment]
If this tool is running, it will automatically reload when the config file is updated.

**Comment by onlyreportingissues** [comment]
> If this tool is running, it will automatically reload when the config file is updated.

Thanks. Also, what happens when I skip configuring it and just use it?

And I'm unfortunately using Fedora which comes with .rpm packages..., do you plan to support .rpm also at some point?

**Comment by Umio-Yasuno** [comment]
> Thanks. Also, are the default configs recommended? I mean can I skip configuring it and just use it?

Setting `perf_level` and `profile` can be skipped, in which case the tool simply does nothing.　　

> And I'm unfortunately using Fedora which comes with .rpm packages..., do you plan to support .rpm also at some point?

The rpm package can be generated by [cargo-generate-rpm](https://github.com/cat-in-136/cargo-generate-rpm), but I don't have the environment so I can't verify it.
