### ISSUE TITLE
[Suggestion] Option to point at a folder also (instead of an application)

### ISSUE THREAD

**Issue by onlyreportingissues** [Umio-Yasuno/amdgpu-profile-switcher#3]
What I imagine is e.g. that one could point to the steamapps folder & the tool will then recognize, if any application is run inside of it & then apply the profile.

It would allow to skip adding every single game to it.

Unrelated: Also, the rpm build didn't work. I hope LACT will implement your tool.

**Comment by Umio-Yasuno** [comment]
> What I imagine is e.g. that one could point to the steamapps folder & the tool will then recognize, if any application is run inside of it & then apply the profile.

Instead of adding that functionality, I think it would be much simpler and easier for users to add config entries like `steam.exe`, `wineserver` and `steam-runtime-launch-client`.
